// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package visibility

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadVisibility returns the embedded CollectionSpec for visibility.
func loadVisibility() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VisibilityBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load visibility: %w", err)
	}

	return spec, err
}

// loadVisibilityObjects loads visibility and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*visibilityObjects
//	*visibilityPrograms
//	*visibilityMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadVisibilityObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadVisibility()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// visibilitySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visibilitySpecs struct {
	visibilityProgramSpecs
	visibilityMapSpecs
	visibilityVariableSpecs
}

// visibilityProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visibilityProgramSpecs struct {
	TracepointSyscallsSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterExecve   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterMmap     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mmap"`
	TracepointSyscallsSysEnterMprotect *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
	TracepointSyscallsSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_recvfrom"`
	TracepointSyscallsSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysExitAccept4   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_accept4"`
}

// visibilityMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visibilityMapSpecs struct {
	AcceptEvents     *ebpf.MapSpec `ebpf:"accept_events"`
	ConnectEvents    *ebpf.MapSpec `ebpf:"connect_events"`
	ExecEvents       *ebpf.MapSpec `ebpf:"exec_events"`
	MmapEvents       *ebpf.MapSpec `ebpf:"mmap_events"`
	MonitoredCgroups *ebpf.MapSpec `ebpf:"monitored_cgroups"`
	MprotectEvents   *ebpf.MapSpec `ebpf:"mprotect_events"`
	SocketDataEvents *ebpf.MapSpec `ebpf:"socket_data_events"`
}

// visibilityVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type visibilityVariableSpecs struct {
}

// visibilityObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadVisibilityObjects or ebpf.CollectionSpec.LoadAndAssign.
type visibilityObjects struct {
	visibilityPrograms
	visibilityMaps
	visibilityVariables
}

func (o *visibilityObjects) Close() error {
	return _VisibilityClose(
		&o.visibilityPrograms,
		&o.visibilityMaps,
	)
}

// visibilityMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadVisibilityObjects or ebpf.CollectionSpec.LoadAndAssign.
type visibilityMaps struct {
	AcceptEvents     *ebpf.Map `ebpf:"accept_events"`
	ConnectEvents    *ebpf.Map `ebpf:"connect_events"`
	ExecEvents       *ebpf.Map `ebpf:"exec_events"`
	MmapEvents       *ebpf.Map `ebpf:"mmap_events"`
	MonitoredCgroups *ebpf.Map `ebpf:"monitored_cgroups"`
	MprotectEvents   *ebpf.Map `ebpf:"mprotect_events"`
	SocketDataEvents *ebpf.Map `ebpf:"socket_data_events"`
}

func (m *visibilityMaps) Close() error {
	return _VisibilityClose(
		m.AcceptEvents,
		m.ConnectEvents,
		m.ExecEvents,
		m.MmapEvents,
		m.MonitoredCgroups,
		m.MprotectEvents,
		m.SocketDataEvents,
	)
}

// visibilityVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadVisibilityObjects or ebpf.CollectionSpec.LoadAndAssign.
type visibilityVariables struct {
}

// visibilityPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadVisibilityObjects or ebpf.CollectionSpec.LoadAndAssign.
type visibilityPrograms struct {
	TracepointSyscallsSysEnterConnect  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterExecve   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterMmap     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mmap"`
	TracepointSyscallsSysEnterMprotect *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mprotect"`
	TracepointSyscallsSysEnterRecvfrom *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_recvfrom"`
	TracepointSyscallsSysEnterSendto   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysExitAccept4   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_accept4"`
}

func (p *visibilityPrograms) Close() error {
	return _VisibilityClose(
		p.TracepointSyscallsSysEnterConnect,
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysEnterMmap,
		p.TracepointSyscallsSysEnterMprotect,
		p.TracepointSyscallsSysEnterRecvfrom,
		p.TracepointSyscallsSysEnterSendto,
		p.TracepointSyscallsSysExitAccept4,
	)
}

func _VisibilityClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed visibility_arm64_bpfel.o
var _VisibilityBytes []byte
