// Code generated by counterfeiter. DO NOT EDIT.
package workerfakes

import (
	"job-worker/internal/worker"
	"job-worker/internal/worker/task"
	"sync"
)

type FakeWorker struct {
	StartJobStub        func(*task.Task) (*task.Task, error)
	startJobMutex       sync.RWMutex
	startJobArgsForCall []struct {
		arg1 *task.Task
	}
	startJobReturns struct {
		result1 *task.Task
		result2 error
	}
	startJobReturnsOnCall map[int]struct {
		result1 *task.Task
		result2 error
	}
	StopJobStub        func(string) error
	stopJobMutex       sync.RWMutex
	stopJobArgsForCall []struct {
		arg1 string
	}
	stopJobReturns struct {
		result1 error
	}
	stopJobReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWorker) StartJob(arg1 *task.Task) (*task.Task, error) {
	fake.startJobMutex.Lock()
	ret, specificReturn := fake.startJobReturnsOnCall[len(fake.startJobArgsForCall)]
	fake.startJobArgsForCall = append(fake.startJobArgsForCall, struct {
		arg1 *task.Task
	}{arg1})
	stub := fake.StartJobStub
	fakeReturns := fake.startJobReturns
	fake.recordInvocation("StartJob", []interface{}{arg1})
	fake.startJobMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeWorker) StartJobCallCount() int {
	fake.startJobMutex.RLock()
	defer fake.startJobMutex.RUnlock()
	return len(fake.startJobArgsForCall)
}

func (fake *FakeWorker) StartJobCalls(stub func(*task.Task) (*task.Task, error)) {
	fake.startJobMutex.Lock()
	defer fake.startJobMutex.Unlock()
	fake.StartJobStub = stub
}

func (fake *FakeWorker) StartJobArgsForCall(i int) *task.Task {
	fake.startJobMutex.RLock()
	defer fake.startJobMutex.RUnlock()
	argsForCall := fake.startJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWorker) StartJobReturns(result1 *task.Task, result2 error) {
	fake.startJobMutex.Lock()
	defer fake.startJobMutex.Unlock()
	fake.StartJobStub = nil
	fake.startJobReturns = struct {
		result1 *task.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeWorker) StartJobReturnsOnCall(i int, result1 *task.Task, result2 error) {
	fake.startJobMutex.Lock()
	defer fake.startJobMutex.Unlock()
	fake.StartJobStub = nil
	if fake.startJobReturnsOnCall == nil {
		fake.startJobReturnsOnCall = make(map[int]struct {
			result1 *task.Task
			result2 error
		})
	}
	fake.startJobReturnsOnCall[i] = struct {
		result1 *task.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeWorker) StopJob(arg1 string) error {
	fake.stopJobMutex.Lock()
	ret, specificReturn := fake.stopJobReturnsOnCall[len(fake.stopJobArgsForCall)]
	fake.stopJobArgsForCall = append(fake.stopJobArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.StopJobStub
	fakeReturns := fake.stopJobReturns
	fake.recordInvocation("StopJob", []interface{}{arg1})
	fake.stopJobMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWorker) StopJobCallCount() int {
	fake.stopJobMutex.RLock()
	defer fake.stopJobMutex.RUnlock()
	return len(fake.stopJobArgsForCall)
}

func (fake *FakeWorker) StopJobCalls(stub func(string) error) {
	fake.stopJobMutex.Lock()
	defer fake.stopJobMutex.Unlock()
	fake.StopJobStub = stub
}

func (fake *FakeWorker) StopJobArgsForCall(i int) string {
	fake.stopJobMutex.RLock()
	defer fake.stopJobMutex.RUnlock()
	argsForCall := fake.stopJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWorker) StopJobReturns(result1 error) {
	fake.stopJobMutex.Lock()
	defer fake.stopJobMutex.Unlock()
	fake.StopJobStub = nil
	fake.stopJobReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeWorker) StopJobReturnsOnCall(i int, result1 error) {
	fake.stopJobMutex.Lock()
	defer fake.stopJobMutex.Unlock()
	fake.StopJobStub = nil
	if fake.stopJobReturnsOnCall == nil {
		fake.stopJobReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.stopJobReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeWorker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.startJobMutex.RLock()
	defer fake.startJobMutex.RUnlock()
	fake.stopJobMutex.RLock()
	defer fake.stopJobMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWorker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ worker.Worker = new(FakeWorker)
