version: "3.0"

# CLI-specific configuration (used by CLI client)
nodes:
  default:
    address: "192.168.1.161:50051"
    cert: |
      -----BEGIN CERTIFICATE-----
      # ... admin client certificate ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      # ... admin client private key ...
      -----END PRIVATE KEY-----
    ca: |
      -----BEGIN CERTIFICATE-----
      # ... CA certificate ...
      -----END CERTIFICATE-----

  viewer:
    address: "192.168.1.161:50051"
    cert: |
      -----BEGIN CERTIFICATE-----
      # ... viewer client certificate (read-only permissions) ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      # ... viewer client private key ...
      -----END PRIVATE KEY-----
    ca: |
      -----BEGIN CERTIFICATE-----
      # ... same CA certificate ...
      -----END CERTIFICATE-----

  production:
    address: "prod-server.company.com:50051"
    cert: |
      -----BEGIN CERTIFICATE-----
      # ... production client certificate ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      # ... production client private key ...
      -----END PRIVATE KEY-----
    ca: |
      -----BEGIN CERTIFICATE-----
      # ... production CA certificate ...
      -----END CERTIFICATE-----

  staging:
    address: "staging-server.company.com:50051"
    cert: |
      -----BEGIN CERTIFICATE-----
      # ... staging client certificate ...
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      # ... staging client private key ...
      -----END PRIVATE KEY-----
    ca: |
      -----BEGIN CERTIFICATE-----
      # ... staging CA certificate ...
      -----END CERTIFICATE-----