version: "3.0"

server:
  address: "0.0.0.0"
  port: 50051
  mode: "server"
  timeout: "10s"

worker:
  defaultCpuLimit: 50              # 50% CPU for development
  defaultMemoryLimit: 256          # 256MB memory limit
  defaultIoLimit: 0                # No I/O limit
  maxConcurrentJobs: 5             # Small number for development
  jobTimeout: "30m"                # 30-minute job timeout
  cleanupTimeout: "2s"             # Quick cleanup
  validateCommands: true           # Enable command validation

security:
  serverCertPath: "/opt/worker/certs/server-cert.pem"
  serverKeyPath: "/opt/worker/certs/server-key.pem"
  caCertPath: "/opt/worker/certs/ca-cert.pem"
  clientCertPath: "/opt/worker/certs/client-cert.pem"
  clientKeyPath: "/opt/worker/certs/client-key.pem"
  minTlsVersion: "1.3"

cgroup:
  baseDir: "/sys/fs/cgroup/worker.slice/worker.service"
  namespaceMount: "/sys/fs/cgroup"
  enableControllers: [ "memory", "cpu" ] # Minimal controllers
  cleanupTimeout: "1s"

filesystem:
  baseDir: "/opt/worker/jobs"              # Base directory for isolated job filesystems
  tmpDir: "/tmp/job-{JOB_ID}"             # Job-specific tmp directory template
  allowedMounts: # Read-only mounts from host system
    - "/usr/bin"                          # Essential binaries
    - "/bin"                              # System binaries
    - "/lib"                              # Libraries
    - "/lib64"                            # 64-bit libraries
    - "/usr/lib"                          # User libraries
    - "/usr/lib64"                        # 64-bit user libraries
  blockDevices: false                     # Block access to devices

grpc:
  maxRecvMsgSize: 262144           # 256KB
  maxSendMsgSize: 1048576          # 1MB
  maxHeaderListSize: 524288        # 512KB
  keepAliveTime: "30s"
  keepAliveTimeout: "5s"

logging:
  level: "DEBUG"                   # Verbose logging for development
  format: "text"                   # Human-readable format
  output: "stdout"                 # Console output
