version: "3.0"

# Server configuration (used by worker daemon)
server:
  address: "192.168.1.161"                             # Will be combined with port if cli.serverAddr not set
  port: 50051
  mode: "server"
  timeout: "10s"
  serverCertPath: "/opt/worker/certs/server-cert.pem"  # Server certificate for TLS
  serverKeyPath: "/opt/worker/certs/server-key.pem"    # Server private key for TLS
  caCertPath: "/opt/worker/certs/ca-cert.pem"          # CA certificate for client validation

# Worker daemon configuration
worker:
  defaultCpuLimit: 50
  defaultMemoryLimit: 256
  defaultIoLimit: 0
  maxConcurrentJobs: 5
  jobTimeout: "30m"
  cleanupTimeout: "2s"
  validateCommands: true

# Cgroup configuration
cgroup:
  baseDir: "/sys/fs/cgroup/worker.slice/worker.service"
  namespaceMount: "/sys/fs/cgroup"
  enableControllers: [ "memory", "cpu" ]
  cleanupTimeout: "1s"

# Filesystem configuration
filesystem:
  baseDir: "/opt/worker/jobs"
  tmpDir: "/tmp/job-{JOB_ID}"
  allowedMounts:
    - "/usr/bin"
    - "/bin"
    - "/lib"
    - "/lib64"
    - "/usr/lib"
    - "/usr/lib64"
  blockDevices: false

# gRPC configuration
grpc:
  maxRecvMsgSize: 262144
  maxSendMsgSize: 1048576
  maxHeaderListSize: 524288
  keepAliveTime: "30s"
  keepAliveTimeout: "5s"

# Logging configuration
logging:
  level: "DEBUG"
  format: "text"
  output: "stdout"