// Code generated by counterfeiter. DO NOT EDIT.
package cloudfakes

import (
	"context"
	"joblet/internal/joblet/monitoring/cloud"
	"joblet/internal/joblet/monitoring/domain"
	"sync"
)

type FakeCloudDetector struct {
	DetectCloudEnvironmentStub        func(context.Context) (*domain.CloudInfo, error)
	detectCloudEnvironmentMutex       sync.RWMutex
	detectCloudEnvironmentArgsForCall []struct {
		arg1 context.Context
	}
	detectCloudEnvironmentReturns struct {
		result1 *domain.CloudInfo
		result2 error
	}
	detectCloudEnvironmentReturnsOnCall map[int]struct {
		result1 *domain.CloudInfo
		result2 error
	}
	GetCachedInfoStub        func() *domain.CloudInfo
	getCachedInfoMutex       sync.RWMutex
	getCachedInfoArgsForCall []struct {
	}
	getCachedInfoReturns struct {
		result1 *domain.CloudInfo
	}
	getCachedInfoReturnsOnCall map[int]struct {
		result1 *domain.CloudInfo
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCloudDetector) DetectCloudEnvironment(arg1 context.Context) (*domain.CloudInfo, error) {
	fake.detectCloudEnvironmentMutex.Lock()
	ret, specificReturn := fake.detectCloudEnvironmentReturnsOnCall[len(fake.detectCloudEnvironmentArgsForCall)]
	fake.detectCloudEnvironmentArgsForCall = append(fake.detectCloudEnvironmentArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DetectCloudEnvironmentStub
	fakeReturns := fake.detectCloudEnvironmentReturns
	fake.recordInvocation("DetectCloudEnvironment", []interface{}{arg1})
	fake.detectCloudEnvironmentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCloudDetector) DetectCloudEnvironmentCallCount() int {
	fake.detectCloudEnvironmentMutex.RLock()
	defer fake.detectCloudEnvironmentMutex.RUnlock()
	return len(fake.detectCloudEnvironmentArgsForCall)
}

func (fake *FakeCloudDetector) DetectCloudEnvironmentCalls(stub func(context.Context) (*domain.CloudInfo, error)) {
	fake.detectCloudEnvironmentMutex.Lock()
	defer fake.detectCloudEnvironmentMutex.Unlock()
	fake.DetectCloudEnvironmentStub = stub
}

func (fake *FakeCloudDetector) DetectCloudEnvironmentArgsForCall(i int) context.Context {
	fake.detectCloudEnvironmentMutex.RLock()
	defer fake.detectCloudEnvironmentMutex.RUnlock()
	argsForCall := fake.detectCloudEnvironmentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCloudDetector) DetectCloudEnvironmentReturns(result1 *domain.CloudInfo, result2 error) {
	fake.detectCloudEnvironmentMutex.Lock()
	defer fake.detectCloudEnvironmentMutex.Unlock()
	fake.DetectCloudEnvironmentStub = nil
	fake.detectCloudEnvironmentReturns = struct {
		result1 *domain.CloudInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudDetector) DetectCloudEnvironmentReturnsOnCall(i int, result1 *domain.CloudInfo, result2 error) {
	fake.detectCloudEnvironmentMutex.Lock()
	defer fake.detectCloudEnvironmentMutex.Unlock()
	fake.DetectCloudEnvironmentStub = nil
	if fake.detectCloudEnvironmentReturnsOnCall == nil {
		fake.detectCloudEnvironmentReturnsOnCall = make(map[int]struct {
			result1 *domain.CloudInfo
			result2 error
		})
	}
	fake.detectCloudEnvironmentReturnsOnCall[i] = struct {
		result1 *domain.CloudInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeCloudDetector) GetCachedInfo() *domain.CloudInfo {
	fake.getCachedInfoMutex.Lock()
	ret, specificReturn := fake.getCachedInfoReturnsOnCall[len(fake.getCachedInfoArgsForCall)]
	fake.getCachedInfoArgsForCall = append(fake.getCachedInfoArgsForCall, struct {
	}{})
	stub := fake.GetCachedInfoStub
	fakeReturns := fake.getCachedInfoReturns
	fake.recordInvocation("GetCachedInfo", []interface{}{})
	fake.getCachedInfoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCloudDetector) GetCachedInfoCallCount() int {
	fake.getCachedInfoMutex.RLock()
	defer fake.getCachedInfoMutex.RUnlock()
	return len(fake.getCachedInfoArgsForCall)
}

func (fake *FakeCloudDetector) GetCachedInfoCalls(stub func() *domain.CloudInfo) {
	fake.getCachedInfoMutex.Lock()
	defer fake.getCachedInfoMutex.Unlock()
	fake.GetCachedInfoStub = stub
}

func (fake *FakeCloudDetector) GetCachedInfoReturns(result1 *domain.CloudInfo) {
	fake.getCachedInfoMutex.Lock()
	defer fake.getCachedInfoMutex.Unlock()
	fake.GetCachedInfoStub = nil
	fake.getCachedInfoReturns = struct {
		result1 *domain.CloudInfo
	}{result1}
}

func (fake *FakeCloudDetector) GetCachedInfoReturnsOnCall(i int, result1 *domain.CloudInfo) {
	fake.getCachedInfoMutex.Lock()
	defer fake.getCachedInfoMutex.Unlock()
	fake.GetCachedInfoStub = nil
	if fake.getCachedInfoReturnsOnCall == nil {
		fake.getCachedInfoReturnsOnCall = make(map[int]struct {
			result1 *domain.CloudInfo
		})
	}
	fake.getCachedInfoReturnsOnCall[i] = struct {
		result1 *domain.CloudInfo
	}{result1}
}

func (fake *FakeCloudDetector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCloudDetector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cloud.CloudDetector = new(FakeCloudDetector)
